name: Bench

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - 'truffleruby'
          - 'jruby'
    name: Benchmark ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Compile
      run: bundle exec rake compile
    - name: Encoder benchmark
      run: bundle exec ruby benchmark.rb
